### ISSUE TITLE
Not working Cordova

### ISSUE THREAD

**Issue by azrulharis** [pubnub/iot-push-demo#1]
Im used this code on index.html. But not working

```
    <div class="app">
        <div id="temperature" class="gears"></div>
        <div id="deviceready">
            <p class="channel blink">Registering Device ID...</p>
        </div>
    </div>
```

**Comment by azrulharis** [comment]
Failed to load resource: the server responded with a status of 403 (Forbidden)

{"status":403,"service":"Access Manager","error":true,"message":"Forbidden","payload":{"channels":["8 code id"]}}

**Comment by keyosk** [comment]
@azrulharis it seems as though you have enabled Access Manager on this subscribe key.

According to the feature toggle: 

> Grant fine-grain access control for all publish and subscribe data. Supports any auth tokens including Google, Facebook or homegrown. **NOTE: Once enabled, and before sending data, you will need to grant permissions first.**

Either turn off Access Manager, or use your secret key to grant an auth token access to this subscribe key and channel, and then perform your device registration using that auth token.

**Comment by azrulharis** [comment]
@keyosk Thanks for your reply. Its work now.
